spring:
  application:
    name: notification-service
  kafka:
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
    bootstrap-servers: localhost:9092

server:
  port: 5000

immino: "globulin"

auth-configuration:
  ApiGatewayUrl: "localhost:9060"
  UaaServerUrl: "uaa-server"
  TokenValidationUrl: "api/token-validation?token"

email-configuration:
  SmtpServer: "smtp.gmail.com"
  SmtpPort: 587
  SmtpUsername: "omrumbakitemiz@gmail.com"
  SmtpPassword: "vrojctjrbzfgbjrf"

eureka:
  "client":
    "serviceUrl": "http://localhost:8090/eureka/"
    "shouldFetchRegistry": false
    "shouldRegisterWithEureka": true
    "validateCertificates": false
  "instance":
    "port": "5000"
    "ipAddress": "localhost"
    "preferIpAddress": true

kafka:
  topic:
    log: system-log

management:
  endpoint:
    health:
      enabled: true
      show-details: always

---

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: e-commerce-notification-service
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: e-commerce-notification-service
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  server:
    host: eureka-server
    port: 8090
  instance:
    prefer-ip-address: true

---

spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: e-commerce-notification-service
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: test
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: e-commerce-notification-service
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true
